logging_dir: logs/coms_cleaned
exp: coms_cleaned
data_dir: data
model_dir: checkpoints/coms_cleaned
task_score_scale: false
task_score_range: (0, 100)
task_relabel: false
task_max_samples:
task_distribution:
task_opt_channel: 2
task_opt_ub: 1.0
task_opt_lb: 0.0
normalize_ys: false
normalize_xs: false
in_latent_space: false
vae_hidden_size: 64
vae_latent_size: 256
vae_activation: relu
vae_kernel_size: 3
vae_num_blocks: 4
vae_lr: 0.0003
vae_beta: 1.0
vae_batch_size: 32
vae_val_size: 200
vae_epochs: 10
particle_lr: 0.05
particle_train_gradient_steps: 50  # 50
particle_evaluate_gradient_steps: 50  # 50
particle_entropy_coefficient: 0.0
forward_model_activations: [nn.ReLU, nn.ReLU, nn.ReLU, nn.ReLU]
forward_model_hidden_size: 128
forward_model_dropout_p: 0.0
forward_model_final_tanh: false
forward_model_lr: 0.0003
forward_model_alpha: 0.1  # 1.0
forward_model_alpha_lr: 0.01
forward_model_overestimation_limit: 0.01
forward_model_noise_std: 0.0
forward_model_batch_size: 2048
forward_model_train_size: 8000
forward_model_val_size: 2000
forward_model_epochs: 200
forward_model_load: false
oracle_ensembles: 5
oracle_activations: [nn.ReLU, nn.ReLU]
oracle_hidden_size: 128
oracle_dropout_p: 0.0
oracle_final_tanh: false
oracle_lr: 0.0003
oracle_noise_std: 0.0
oracle_batch_size: 128  # 2048
oracle_val_size: 20000
oracle_epochs: 200
oracle_load: true
evaluation_samples: [50,2]
fast: false