exp: romo
logging_dir: logs/romo/dkitty
model_dir: checkpoints/romo/dkitty
task: DKittyMorphology-Exact-v0
task_relabel: false
task_opt_channel: 50
normalize_ys: true
normalize_xs: true
dimension_oriented: false
size_retrieval_set: 10
retrieval_method: cosine
particle_lr: 0.005  #
particle_gradient_steps: 50  #
particle_entropy_coefficient: 0.0
forward_model_activations: [nn.ReLU, nn.ReLU]
forward_model_hidden_size: 2048
forward_model_dropout_p: 0.0
forward_model_final_tanh: false
forward_model_lr: 0.0003
forward_model_alpha: 0.1
forward_model_alpha_lr: 0.01
forward_model_overestimation_limit: 0.5 # 0.01
forward_model_noise_std: 0.0
forward_model_batch_size: 128  #
forward_model_val_size: 500  #
forward_model_train_ratio: 0.8
forward_model_epochs: 200  #
forward_model_aggregation_method: ridge
forward_model_load: false
forward_model_weights: [0.5, 0.5] # [f(x,R(x)), f(x)]
mse_loss_weight: 1 # mse_loss(f(x),f(x,R(x)))
evaluation_samples: 128
fast: false
# train_ratio forward_model_epochs mse_loss_weight overestimation_limit particle_lr&steps