exp: rim
logging_dir: logs/rim/nas
model_dir: checkpoints/rim/nas
task: NASBench-Exact-v0
task_relabel: false
task_opt_channel: 30
normalize_ys: true
normalize_xs: true
size_retrieval_set: 10
retrieval_method: cosine
particle_lr: 0.05  #
particle_gradient_steps: 50  #
particle_entropy_coefficient: 0.0
forward_model_activations: [nn.ReLU, nn.ReLU]
forward_model_hidden_size: 2048
forward_model_dropout_p: 0.0
forward_model_final_tanh: false
forward_model_lr: 0.0003
forward_model_noise_std: 0.0
forward_model_batch_size: 2048  #
forward_model_val_size: 5000  #
forward_model_train_ratio: 0.5
forward_model_epochs: 50  #
forward_model_aggregation_method: ridge
forward_model_load: false
evaluation_samples: 128
fast: false