python main.py -c genetic
python main.py -c genetic
python main.py -c genetic
python main.py -c genetic
python main.py -c genetic
python main.py -c genetic
python main.py -c genetic
python main.py -c genetic
python main.py -c genetic
python main.py -c genetic

python main.py -c gradient_ascent
python main.py -c gradient_ascent
python main.py -c gradient_ascent
python main.py -c gradient_ascent
python main.py -c gradient_ascent
python main.py -c gradient_ascent
python main.py -c gradient_ascent
python main.py -c gradient_ascent
python main.py -c gradient_ascent
python main.py -c gradient_ascent

python main.py -c iom
python main.py -c iom
python main.py -c iom
python main.py -c iom
python main.py -c iom
python main.py -c iom
python main.py -c iom
python main.py -c iom
python main.py -c iom
python main.py -c iom

python main.py -c romo
python main.py -c romo
python main.py -c romo
python main.py -c romo
python main.py -c romo
python main.py -c romo
python main.py -c romo
python main.py -c romo
python main.py -c romo
python main.py -c romo

python main.py -c rim
python main.py -c rim
python main.py -c rim
python main.py -c rim
python main.py -c rim
python main.py -c rim
python main.py -c rim
python main.py -c rim
python main.py -c rim
python main.py -c rim

python main.py -c coms_cleaned
python main.py -c coms_cleaned
python main.py -c coms_cleaned
python main.py -c coms_cleaned
python main.py -c coms_cleaned
python main.py -c coms_cleaned
python main.py -c coms_cleaned
python main.py -c coms_cleaned
python main.py -c coms_cleaned
python main.py -c coms_cleaned

python visualization/analysis.py -p genetic
python visualization/analysis.py -p gradient_ascent
python visualization/analysis.py -p iom
python visualization/analysis.py -p romo
python visualization/analysis.py -p rim
python visualization/analysis.py -p coms_cleaned